version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
configuration: RelWithDebInfo
platform: x64
before_build:
- cmd: >-
    echo Building the commit %APPVEYOR_REPO_COMMIT%
        
    git submodule init

    git submodule update --init --recursive

    vcsetup.bat
build:
  project: build\gltf-insight.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: build\RelWithDebInfo\gltf-insight.exe
- path: build\RelWithDebInfo\gltf-insight.pdb
deploy:
- provider: GitHub
  tag: continuous-appveyor
  release: "Windows continuous build"
  description: "AppVeyor build $(appveyor_repo_commit)"
  auth_token:
    secure: 0ewOMT51w2I41galWFJsoJp/SQyOjtljI0RAn/P4Z62JbcOiOHVT06SWxpfWVODc
  prerelease: true
  force_update: true
  on:
    branch: devel
