version: 1.0.{build}
image: Visual Studio 2017
platform: x64
before_build:
- cmd: >-
    git submodule init

    git submodule update

    vcsetup.bat
build:
  project: build\gltf-insight.sln
  parallel: true
  verbosity: minimal
